MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Models/Sede.cs
using System;
using System.Collections.Generic;

namespace MiPrimeraAplicacionEnNetCore.Models
{
    public partial class Sede
    {
        public Sede()
        {
            Cita = new HashSet<Citum>();
            Doctors = new HashSet<Doctor>();
        }

        public int Iidsede { get; set; }
        public string? Nombre { get; set; }
        public string? Direccion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Citum> Cita { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Controllers/SedeController.cs
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAplicacionEnNetCore.Clases;
using MiPrimeraAplicacionEnNetCore.Models;

namespace MiPrimeraAplicacionEnNetCore.Controllers
{
    public class SedeController : Controller
    {
        public IActionResult Index(SedeCLS oSedeCLS)
        {

            List<SedeCLS> listaSede = new List<SedeCLS>();
            using(BDHospitalContext db = new BDHospitalContext())
            {
                if(oSedeCLS.nombreSede == "" || oSedeCLS.nombreSede == null )
                {
                    listaSede = (from sede in db.Sedes
                            where sede.Bhabilitado == 1
                            select new SedeCLS
                            {
                                iidSede = sede.Iidsede,
                                nombreSede = sede.Nombre,
                                direccion = sede.Direccion
                            }).ToList();
                    ViewBag.nombreSede = "";
                } else
                {
                    listaSede = (from sede in db.Sedes
                                 where sede.Bhabilitado == 1
                                 && sede.Nombre.Contains(oSedeCLS.nombreSede)
                                 select new SedeCLS
                                 {
                                     iidSede = sede.Iidsede,
                                     nombreSede = sede.Nombre,
                                     direccion = sede.Direccion
                                 }).ToList();
                    ViewBag.nombreSede = oSedeCLS.nombreSede;
                }

            }
            
            return View(listaSede);

        }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Views/Sede/Index.cshtml
@model IEnumerable<MiPrimeraAplicacionEnNetCore.Clases.SedeCLS>

@{
    ViewData["Title"] = "Index";
    string nombreSede = ViewBag.nombreSede;
}

<form id="formEnviar" asp-controller="Sede" asp-action="Index" class="mb-2" method="post">
    <label>Ingrese Sede</label>
    <input type="text" class="form form-control" name="nombreSede" value="@nombreSede" onkeyup="Buscar()" />

</form>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.iidSede)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombreSede)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.iidSede)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombreSede)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.direccion)
            </td>
        </tr>
}
    </tbody>
</table>

<script>

    function Buscar() {
        document.getElementById("formEnviar").submit();
    }

</script>