MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Models/TipoUsuario.cs
using System;
using System.Collections.Generic;

namespace MiPrimeraAplicacionEnNetCore.Models
{
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            TipoUsuarioPaginas = new HashSet<TipoUsuarioPagina>();
            Usuarios = new HashSet<Usuario>();
        }

        public int Iidtipousuario { get; set; }
        public string? Nombre { get; set; }
        public string? Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<TipoUsuarioPagina> TipoUsuarioPaginas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Controllers/TipoUsuarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAplicacionEnNetCore.Clases;
using MiPrimeraAplicacionEnNetCore.Models;

namespace MiPrimeraAplicacionEnNetCore.Controllers
{
    public class TipoUsuarioController : Controller
    {
        // GET: TipoUsuario
        public ActionResult Index(TipoUsuarioCLS oTipoUsuarioCLS)
        {
            List<TipoUsuarioCLS> listaTipoUsu = new List<TipoUsuarioCLS>();
            using(BDHospitalContext db = new BDHospitalContext())
            {
                listaTipoUsu = (from tipousu in db.TipoUsuarios
                                where tipousu.Bhabilitado == 1
                                select new TipoUsuarioCLS
                                {
                                    iidTipoUsuario = tipousu.Iidtipousuario,
                                    nombre = tipousu.Nombre,
                                    descripcion = tipousu.Descripcion
                                }).ToList();
            if(oTipoUsuarioCLS.nombre == null && oTipoUsuarioCLS.descripcion == null && oTipoUsuarioCLS.iidTipoUsuario == 0)
                {
                    ViewBag.Nombre = "";
                    ViewBag.Descripcion = "";
                    ViewBag.IidTipoUsuario = 0;
                }
                else
                {
                    if(oTipoUsuarioCLS.nombre != null)
                    {
                        listaTipoUsu = listaTipoUsu.Where(p => p.nombre.Contains(oTipoUsuarioCLS.nombre)).ToList();
                    }
                    if (oTipoUsuarioCLS.iidTipoUsuario != 0)
                    {
                        listaTipoUsu = listaTipoUsu.Where(p => p.iidTipoUsuario == oTipoUsuarioCLS.iidTipoUsuario).ToList();
                    }
                    if (oTipoUsuarioCLS.descripcion != null)
                    {
                        listaTipoUsu = listaTipoUsu.Where(p => p.descripcion.Contains(oTipoUsuarioCLS.nombre)).ToList();
                    }
                    ViewBag.Nombre = oTipoUsuarioCLS.nombre;
                    ViewBag.Descripcion = oTipoUsuarioCLS.descripcion;
                    ViewBag.IidTipoUsuario = oTipoUsuarioCLS.iidTipoUsuario;
                }
            }
            return View(listaTipoUsu);
        }

        // GET: TipoUsuario/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TipoUsuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoUsuario/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoUsuario/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TipoUsuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TipoUsuario/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TipoUsuario/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Views/TipoUsuario/Index.cshtml
@model IEnumerable<MiPrimeraAplicacionEnNetCore.Clases.TipoUsuarioCLS>

@{
    ViewData["Title"] = "Index";

    string nombre = ViewBag.Nombre;
    string descripcion = ViewBag.Descripcion;
    int iidtipousuario = ViewBag.IidTipoUsuario;

}

<h1>Index</h1>

<form asp-controller="TipoUsuario" asp-action="Index">
    <input type="submit" value="Enviar" class="btn btn-primary"/>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.iidTipoUsuario)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.descripcion)
                </th>
            </tr>
            <tr>
                <th>
                    @if(iidtipousuario == 0)
                    {
                    <input type="number" name="iidTipoUsuario" class="form form-control" />
                    } else {
                    <input type="number" value="@iidtipousuario" name="iidTipoUsuario" class="form form-control" />
                    }
                </th>
                <th>
                    <input type="text" value="@nombre" name="nombre" class="form form-control" />
                </th>
                <th>
                    <input type="text" value="@descripcion" name="descripcion" class="form form-control" />
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.iidTipoUsuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
            </tr>
            }


        </tbody>
    </table>
</form>