MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Models/Especialidad.cs
using System;
using System.Collections.Generic;

namespace MiPrimeraAplicacionEnNetCore.Models
{
    public partial class Especialidad
    {
        public Especialidad()
        {
            Doctors = new HashSet<Doctor>();
        }

        public int Iidespecialidad { get; set; }
        public string? Nombre { get; set; }
        public string? Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Controllers/EspecialidadController.cs
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAplicacionEnNetCore.Clases;
using MiPrimeraAplicacionEnNetCore.Models;

namespace MiPrimeraAplicacionEnNetCore.Controllers
{
    public class EspecialidadController : Controller
    {
        public IActionResult Index(EspecialidadCLS oEspecialidadCLS)
        {
            ViewBag.nombreEspecialidad = "";
            List<EspecialidadCLS> listaEspecialidad = new List<EspecialidadCLS>();
            using (BDHospitalContext db = new BDHospitalContext()){
            if(oEspecialidadCLS.nombre == null || oEspecialidadCLS.nombre == "") {
                    listaEspecialidad = (from especialidad in db.Especialidads
                                         where especialidad.Bhabilitado == 1
                                         select new EspecialidadCLS
                                         {
                                             iidespecialidad = especialidad.Iidespecialidad,
                                             nombre = especialidad.Nombre,
                                             descripcion = especialidad.Descripcion
                                         }).ToList();
                    ViewBag.nombreEspecialidad = "";
            } 
            else 
            {
                    listaEspecialidad = (from especialidad in db.Especialidads
                                        where especialidad.Bhabilitado == 1
                                        && especialidad.Nombre.Contains(oEspecialidadCLS.nombre) // importante acá debe estar correctamente detallado como name del input text donde mostrar con el valor del atributo en este caso nombre
                                        select new EspecialidadCLS
                                        {
                                             iidespecialidad = especialidad.Iidespecialidad,
                                             nombre = especialidad.Nombre,
                                             descripcion = especialidad.Descripcion
                                        }).ToList();
                    ViewBag.nombreEspecialidad = oEspecialidadCLS.nombre;
                    }
            }
            return View(listaEspecialidad);
        }

        public IActionResult Agregar() 
        {
            return View();        
        }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Views/Especialidad/Agregar.cshtml
@using MiPrimeraAplicacionEnNetCore.Clases;
@model EspecialidadCLS
@{
    ViewData["Title"] = "Agregar";
}

<h1>Crear una especialidad</h1>

<hr />

<div class="row">
    <div class="col-md-6">
        <form asp-action="">
            <div class="form-group">
                <label asp-for="nombre"></label>
                <input asp-for="nombre" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="descripcion"></label>
                <input asp-for="descripcion" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-danger">Regresar</a>
            </div>
        </form>
    </div>
</div>

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Views/Especialidad/Index.cshtml
@using MiPrimeraAplicacionEnNetCore.Clases;
@model IEnumerable<EspecialidadCLS>
@{
    ViewData["Title"] = "Index";
    string nombreEspecialidad = ViewBag.nombreEspecialidad;
}
<a class="btn btn-secondary" asp-action="Agregar" asp-controller="Especialidad">Agregar</a>
<form asp-controller="Especialidad" asp-action="Index" method="post" class="mb-2"
      style="display:grid;grid-template-columns:1fr 2fr 1fr 1fr" id="filterForm">

    <label>Ingrese Especialidad</label>
    <input type="text" class="form form-control" name="nombre" value="@nombreEspecialidad" id="nombre"/>
    <input type="submit" value="Enviar" class="btn btn-info" />
    <input type="button" value="Limpiar" class="btn btn-danger" onclick="Limpiar()"/>
</form>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model=>model.iidespecialidad)</th>
            <th>@Html.DisplayNameFor(model=>model.nombre)</th>
            <th>@Html.DisplayNameFor(model=>model.descripcion)</th>
        </tr>
    </thead>
    <tbody>
        @foreach(EspecialidadCLS oEspecialidad in Model)
        {
            <tr>
                <td>@oEspecialidad.iidespecialidad</td>
                <td>@oEspecialidad.nombre</td>
                <td>@oEspecialidad.descripcion</td>
            </tr>
        }



    </tbody>
</table>

<script>

    function Limpiar() {
        document.getElementById("nombre").value = "";
        document.getElementById("filterForm").submit();
    }

</script>