MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Models/Pagina.cs
using System;
using System.Collections.Generic;

namespace MiPrimeraAplicacionEnNetCore.Models
{
    public partial class Pagina
    {
        public Pagina()
        {
            TipoUsuarioPaginas = new HashSet<TipoUsuarioPagina>();
        }

        public int Iidpagina { get; set; }
        public string? Mensaje { get; set; }
        public string? Accion { get; set; }
        public string? Controlador { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<TipoUsuarioPagina> TipoUsuarioPaginas { get; set; }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Controllers/PaginaController.cs
using Microsoft.AspNetCore.Mvc;
using MiPrimeraAplicacionEnNetCore.Clases;
using MiPrimeraAplicacionEnNetCore.Models;

namespace MiPrimeraAplicacionEnNetCore.Controllers
{
    public class PaginaController : Controller
    {
        public IActionResult Index(PaginaCLS oPaginaCLS)
        {
            List<PaginaCLS> listaPagina = new List<PaginaCLS>();
            using(BDHospitalContext db = new BDHospitalContext())
            {
                listaPagina = (from pagina in db.Paginas
                              where pagina.Bhabilitado == 1
                              select new PaginaCLS
                              {
                                  iidPagina = pagina.Iidpagina,
                                  mensaje = pagina.Mensaje,
                                  accion = pagina.Accion,
                                  controlador = pagina.Controlador
                              }).ToList();
                if(oPaginaCLS.mensaje == null)
                {
                    ViewBag.Mensaje = "";
                } else
                {
                    if(oPaginaCLS.mensaje != null)
                    {
                        listaPagina = listaPagina.Where(p => p.mensaje.Contains(oPaginaCLS.mensaje)).ToList();
                    }
                    ViewBag.Mensaje = oPaginaCLS.mensaje;
                }
            }


            return View(listaPagina);
        }
    }
}

MiPrimeraAplicacionEnNetCore/MiPrimeraAplicacionEnNetCore/Views/Pagina/Index.cshtml
@using MiPrimeraAplicacionEnNetCore.Clases;
@model IEnumerable<PaginaCLS>

@{
    ViewData["Title"] = "Index";

    string mensaje = ViewBag.mensaje;
}


<form asp-asp-controller="Pagina" asp-action="Index" id="filterForm">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <label>IngreseMensaje</label>
                <input type="text" value="@mensaje" name="mensaje" class="form form-control" id="mensaje"/>
                <input type="submit" value="Enviar" class="btn btn-primary"/>
                <input type="button" value="Limpiar" class="btn btn-danger" onclick="Limpiar()"/>
            </tr>
        </thead>
    </table>    
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ID Pagina</th>
                <th>Mensaje</th>
                <th>@Html.DisplayNameFor(model=>model.accion)</th>
                <th>@Html.DisplayNameFor(model=>model.controlador)</th>
            </tr>
        </thead>
        <tbody>
            @foreach(PaginaCLS oPaginCLS in Model)
            {
                <tr>
                    <td>@oPaginCLS.iidPagina</td>
                    <td>@oPaginCLS.mensaje</td>
                    <td>@oPaginCLS.accion</td>
                    <td>@oPaginCLS.controlador</td>
                </tr>
            }


        </tbody>

    </table>

</form>

<script>
    function Limpiar() {
        document.getElementById("mensaje").value = "";
        document.getElementById("filterForm").submit();
    }
</script>